notARepository: "quit"
os:
  editPreset: nvim
gui:
  sidePanelWidth: 0.3
  showBottomLine: false
  theme:
    activeBorderColor:
      - "#ed7bcd"
      - "bold"
    inactiveBorderColor:
      - "#D4BE98"
    selectedLineBgColor:
      - "black"
    selectedRangeBgColor:
      - "black"
      - "bold"
    unstagedChangesColor:
      - "#eba721"
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" # useConfig: false
